=== michiexile/xkcd-1688/xkcd1688.dtd
<!ELEMENT xkcd1688 (node|leaf)+>
<!ELEMENT node (question,option+,range+)>
<!ATTLIST node id ID #REQUIRED>
<!ELEMENT option (#PCDATA)>
<!ATTLIST option target IDREF #IMPLIED>
<!ELEMENT question (#PCDATA)>
<!ELEMENT range (begin, end)>
<!ELEMENT begin EMPTY>
<!ATTLIST begin year CDATA #REQUIRED>
<!ELEMENT end EMPTY>
<!ATTLIST end year CDATA #REQUIRED>
<!ELEMENT leaf (#PCDATA|range)*>
<!ATTLIST leaf id ID #REQUIRED>

=== michiexile/xkcd-1688/xkcd1688.xml
<?xml version="1.0"?>
<!DOCTYPE xkcd1688 SYSTEM "xkcd1688.dtd">


<xkcd1688>
  <node id="root">
    <question>
      Start here
    </question>
    <option target="istanbul">
      Go
    </option>
    <range>
      <begin year="" />
      <end year="" />
    </range>
  </node>
  
  <node id="istanbul">
    <question>
      Istanbul or Constantinople?
    </question>
    <option target="canada-alaska-tokyo">
      Constantinople
    </option>
    <option target="ottoman-exist">
      Neither
    </option>
    <option target="istanbul-and-sovie">
      Istanbul
    </option>
    <range>
      <begin year="" />
      <end year="" />
    </range>
  </node>

  <node id="canada-alaska-tokyo">
    <question>
      Do any of these exist?
      Independent Canada?
      US Territory of Alaska?
      Tokyo?
    </question>
    <option target="holy-roman-empire">
      No
    </option>
    <option target="south-africa">
      Yes
    </option>
    <range>
      <begin year="" />
      <end year="1928" />
    </range>
  </node>      
  
  <node id="holy-roman-empire">
    <question>
      The Holy Roman Empire?
    </question>
    <option target="hre-yes">
      Yes
    </option>
    <option target="US">
      No
    </option>
    <range>
      <begin year="" />
      <end year="1867" />
    </range>
  </node>

  <leaf id="hre-yes">
    1805 or earlier (before this point the modern idea of a
    complete political map of the world gets hard to apply)
  </leaf>

  <node id="US">
    <question>
      The United States?
    </question>
    <option target="no-us">
      No
    </option>
    <option target="texas-is">
      Yes
    </option>
    <range>
      <begin year="1806" />
      <end year="1867" />
    </range>
  </node>

  <leaf id="no-us">
    How sure are you that this map is in English?
  </leaf>

  <node id="texas-is">
    <question>
      Texas is...
    </question>
    <option target="florida-is">
      Part of Mexico
    </option>
    <option target="texas-independent">
      Independent
    </option>
    <option target="russia-sea-of-japan">
      Part of the US
    </option>
    <range>
      <begin year="1806" />
      <end year="1867" />
    </range>
  </node>

  <node id="florida-is">
    <question>
      Florida is parth of...
    </question>
    <option target="paraguay">
      Spain
    </option>
    <option target="venezuela-ecuador">
      US
    </option>
    <range>
      <begin year="1806" />
      <end year="1836" />
    </range>
  </node>

  <node id="paraguay">
    <question>
      Paraguay?
    </question>
    <option target="paraguay-no">
      No
    </option>
    <option target="paraguay-yes">
      Yes
    </option>
    <range>
      <begin year="1806" />
      <end year="1817" />
    </range>
  </node>

  <leaf id="paraguay-no">
    <range>
      <begin year="1806" />
      <end year="1810" />
    </range>
  </leaf>
  <leaf id="paraguay-yes">
    <range>
      <begin year="1811" />
      <end year="1817" />
    </range>
  </leaf>

  <node id="venezuela-ecuador">
    <question>
      Venezuela and/or Ecuador?
    </question>
    <option target="venezuela-ecuador-no">
      No
    </option>
    <option target="venezuela-ecuador-yes">
      Yes
    </option>
    <range>
      <begin year="1818" />
      <end year="1833" />
    </range>
  </node>

  <leaf id="venezuela-ecuador-no">
    <range>
      <begin year="1818" />
      <end year="1829" />
    </range>
  </leaf>
  <leaf id="venezuela-ecuador-yes">
    <range>
      <begin year="1830" />
      <end year="1833" />
    </range>
  </leaf>

  <leaf id="texas-independent">
    <range>
      <begin year="1834" />
      <end year="1845" />
    </range>
  </leaf>
  
  <node id="russia-sea-of-japan">
    <question>
      Does Russia border the Sea of Japan?
    </question>
    <option target="us-southern-border">
      No
    </option>
    <option target="russia-sea-of-japan-yes">
      Yes
    </option>
    <range>
      <begin year="1846" />
      <end year="1867" />
    </range>
  </node>

  <node id="us-southern-border">
    <question>
      The USs southern border looks...
    </question>
    <option target="us-southern-weird">
      Weird
    </option>
    <option target="us-southern-normal">
      Normal
    </option>
    <range>
      <begin year="1846" />
      <end year="1856" />
    </range>
  </node>

  <leaf id="russia-sea-of-japan-yes">
    <range>
      <begin year="1858" />
      <end year="1867" />
    </range>
  </leaf>
  <leaf id="us-southern-weird">
    <range>
      <begin year="1846" />
      <end year="1853" />
    </range>
  </leaf>
  <leaf id="us-southern-normal">
    <range>
      <begin year="1854" />
      <end year="1856" />
    </range>
  </leaf>

  <node id="south-africa">
    <question>
      South Africa?
    </question>
    <option target="rhodesia">
      No
    </option>
    <option target="austria-hungary">
      Yes
    </option>
    <range>
      <begin year="1868" />
      <end year="1928" />
    </range>
  </node>

  <node id="rhodesia">
    <question>
      Rhodesia?
    </question>
    <option target="bolivia-landlocked">
      No
    </option>
    <option target="norway-in-sweden">
      Yes
    </option>
    <range>
      <begin year="1868" />
      <end year="1910" />
    </range>
  </node>

  <node id="bolivia-landlocked">
    <question>
      Is Bolivia landlocked?
    </question>
    <option target="buda-pest-budapest">
      No
    </option>
    <option target="bolivia-is-landlocked">
      Yes
    </option>
    <range>
      <begin year="1868" />
      <end year="1895" />
    </range>
  </node>

  <leaf id="bolivia-is-landlocked">
    <range>
      <begin year="1884" />
      <end year="1895" />
    </range>
  </leaf>
  
  <node id="buda-pest-budapest">
    <question>
      "Buda" and "Pest" or "Budapest"?
    </question>
    <option target="buda-pest">
      Buda and Pest
    </option>
    <option target="budapest">
      Budapest
    </option>
    <range>
      <begin year="1868" />
      <end year="1884" />
    </range>
  </node>
  <leaf id="buda-pest">
    <range>
      <begin year="1868" />
      <end year="1872" />
    </range>
  </leaf>
  <leaf id="budapest">
    <range>
      <begin year="1873" />
      <end year="1884" />
    </range>
  </leaf>

  <node id="norway-in-sweden">
    <question>
      Is Norway part of Sweden?
    </question>
    <option target="norway-is-sweden">
      Yes
    </option>
    <option target="norway-not-sweden">
      No
    </option>
    <range>
      <begin year="1895" />
      <end year="1910" />
    </range>
  </node>
  <leaf id="norway-is-sweden">
    <range>
      <begin year="1895" />
      <end year="1905" />
    </range>
  </leaf>
  <leaf id="norway-not-sweden">
    <range>
      <begin year="1906" />
      <end year="1910" />
    </range>
  </leaf>

  <node id="austria-hungary">
    <question>
      Austria-Hungary?
    </question>
    <option target="albania">
      Yes
    </option>
    <option target="leningrad">
      No
    </option>
    <range>
      <begin year="1910" />
      <end year="1928" />
    </range>
  </node>

  <node id="albania">
    <question>
      Albania?
    </question>
    <option target="albania-no">
      No
    </option>
    <option target="albania-yes">
      Yes
    </option>
    <range>
      <begin year="1910" />
      <end year="1918" />
    </range>
  </node>
  <leaf id="albania-no">
    <range>
      <begin year="1910" />
      <end year="1912" />
    </range>
  </leaf>
  <leaf id="albania-yes">
    <range>
      <begin year="1913" />
      <end year="1918" />
    </range>
  </leaf>



  <node id="leningrad">
    <question>
      Leningrad?
    </question>
    <option target="leningrad-no">
      No
    </option>
    <option target="leningrad-yes">
      Yes
    </option>
    <range>
      <begin year="1918" />
      <end year="1928" />
    </range>
  </node>
  <leaf id="leningrad-no">
    <range>
      <begin year="1918" />
      <end year="1923" />
    </range>
  </leaf>
  <leaf id="leningrad-yes">
    <range>
      <begin year="1924" />
      <end year="1929" />
    </range>
  </leaf>


  <node id="istanbul-soviet">
    <question>
      Does the Soviet Union exist?
    </question>
    <option target="west-africa-french">
      Yes
    </option>
    <option target="zaire-hongkonguk">
      No
    </option>
    <range>
      <begin year="1928" />
      <end year="" />
    </range>
  </node>

  <node id="west-africa-french">
    <question>
      Is most of West Africa a giant French blob?
    </question>
    <option target="pakistan">
      Yes
    </option>
    <option target="how-many-vietnam">
      No
    </option>
    <range>
      <begin year="1928" />
      <end year="1991" />
    </range>
  </node>

  <node id="pakistan">
    <question>
      Pakistan?
    </question>
    <option target="how-many-germany">
      No
    </option>
    <option target="cambodia">
      Yes
    </option>
    <range>
      <begin year="1928" />
      <end year="1960" />
    </range>
  </node>

  <node id="how-many-germany">
    <question>
      How many Germanys are there?
    </question>
    <option target="persia-iran">
      One
    </option>
    <option target="one-large-germany">
      One, but it's huge.
    </option>
    <option target="two-germany">
      Two
    </option>
    <range>
      <begin year="1928" />
      <end year="1947" />
    </range>
  </node>
  <leaf id="one-large-germany">
    <range>
      <begin year="1941" />
      <end year="1945" />
    </range>
  </leaf>
  <leaf id="two=germany">
    <range>
      <begin year="1946" />
      <end year="1947" />
    </range>
  </leaf>

  <node id="persia-iran">
    <question>
      Persia or Iran?
    </question>
    <option target="persia">
      Persia
    </option>
    <option target="iran">
      Iran
    </option>
    <range>
      <begin year="1928" />
      <end year="1940" />
    </range>
  </node>

  <leaf id="persia">
    <range>
